# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# 'base/settings/Ui_options.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from qgis.PyQt import QtCore, QtGui, QtWidgets


class Ui_Options(object):
    def setupUi(self, Options):
        Options.setObjectName("Options")
        Options.resize(542, 474)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Options.sizePolicy().hasHeightForWidth())
        Options.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Options)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Options)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setEnabled(True)
        self.tabGeneral.setObjectName("tabGeneral")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabGeneral)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40,
                                           QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tabGeneral)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditProjectsDatabase = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditProjectsDatabase.setObjectName("lineEditProjectsDatabase")
        self.gridLayout_3.addWidget(self.lineEditProjectsDatabase, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.btnBrowseProjectsDatabase = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowseProjectsDatabase.setObjectName(
                "btnBrowseProjectsDatabase")
        self.gridLayout_3.addWidget(self.btnBrowseProjectsDatabase, 0, 2, 1, 1)
        self.btnBrowseProjectsRootDir = QtWidgets.QPushButton(self.groupBox)
        self.btnBrowseProjectsRootDir.setObjectName("btnBrowseProjectsRootDir")
        self.gridLayout_3.addWidget(self.btnBrowseProjectsRootDir, 1, 2, 1, 1)
        self.lineEditProjectsRootDir = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditProjectsRootDir.setObjectName("lineEditProjectsRootDir")
        self.gridLayout_3.addWidget(self.lineEditProjectsRootDir, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.btnTestProjectDB = QtWidgets.QPushButton(self.groupBox)
        self.btnTestProjectDB.setObjectName("btnTestProjectDB")
        self.gridLayout_12.addWidget(self.btnTestProjectDB, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tabImport = QtWidgets.QWidget()
        self.tabImport.setObjectName("tabImport")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabImport)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabImport)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.lineEditImportJar = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditImportJar.setObjectName("lineEditImportJar")
        self.horizontalLayout.addWidget(self.lineEditImportJar)
        self.btnBrowseImportJar = QtWidgets.QPushButton(self.groupBox_3)
        self.btnBrowseImportJar.setObjectName("btnBrowseImportJar")
        self.horizontalLayout.addWidget(self.btnBrowseImportJar)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabImport)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.plainTextEditImportVMArguments = QtWidgets.QPlainTextEdit(
                self.groupBox_2)
        self.plainTextEditImportVMArguments.setPlainText("")
        self.plainTextEditImportVMArguments.setObjectName(
                "plainTextEditImportVMArguments")
        self.gridLayout_8.addWidget(self.plainTextEditImportVMArguments, 0, 0,
                                    1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabImport, "")
        self.tabDatabase = QtWidgets.QWidget()
        self.tabDatabase.setObjectName("tabDatabase")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabDatabase)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabDatabase)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lblDbAdminPwd = QtWidgets.QLabel(self.groupBox_5)
        self.lblDbAdminPwd.setObjectName("lblDbAdminPwd")
        self.gridLayout_10.addWidget(self.lblDbAdminPwd, 6, 0, 1, 1)
        self.lineEditDbUserPwd = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditDbUserPwd.setEchoMode(
                QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEditDbUserPwd.setObjectName("lineEditDbUserPwd")
        self.gridLayout_10.addWidget(self.lineEditDbUserPwd, 4, 1, 1, 1)
        self.lineEditDbPort = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditDbPort.setObjectName("lineEditDbPort")
        self.gridLayout_10.addWidget(self.lineEditDbPort, 2, 1, 1, 1)
        self.lblDbAdmin = QtWidgets.QLabel(self.groupBox_5)
        self.lblDbAdmin.setObjectName("lblDbAdmin")
        self.gridLayout_10.addWidget(self.lblDbAdmin, 5, 0, 1, 1)
        self.lineEditDbAdminPwd = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditDbAdminPwd.setEchoMode(
                QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEditDbAdminPwd.setObjectName("lineEditDbAdminPwd")
        self.gridLayout_10.addWidget(self.lineEditDbAdminPwd, 6, 1, 1, 1)
        self.lblDbPort = QtWidgets.QLabel(self.groupBox_5)
        self.lblDbPort.setObjectName("lblDbPort")
        self.gridLayout_10.addWidget(self.lblDbPort, 2, 0, 1, 1)
        self.lineEditDbHost = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditDbHost.setObjectName("lineEditDbHost")
        self.gridLayout_10.addWidget(self.lineEditDbHost, 0, 1, 1, 1)
        self.lineEditDbDatabase = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditDbDatabase.setObjectName("lineEditDbDatabase")
        self.gridLayout_10.addWidget(self.lineEditDbDatabase, 1, 1, 1, 1)
        self.lineEditDbAdmin = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditDbAdmin.setObjectName("lineEditDbAdmin")
        self.gridLayout_10.addWidget(self.lineEditDbAdmin, 5, 1, 1, 1)
        self.lblDbUserPwd = QtWidgets.QLabel(self.groupBox_5)
        self.lblDbUserPwd.setObjectName("lblDbUserPwd")
        self.gridLayout_10.addWidget(self.lblDbUserPwd, 4, 0, 1, 1)
        self.lblDbDatabase = QtWidgets.QLabel(self.groupBox_5)
        self.lblDbDatabase.setObjectName("lblDbDatabase")
        self.gridLayout_10.addWidget(self.lblDbDatabase, 1, 0, 1, 1)
        self.lblDbHost = QtWidgets.QLabel(self.groupBox_5)
        self.lblDbHost.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblDbHost.setObjectName("lblDbHost")
        self.gridLayout_10.addWidget(self.lblDbHost, 0, 0, 1, 1)
        self.lblDbUser = QtWidgets.QLabel(self.groupBox_5)
        self.lblDbUser.setObjectName("lblDbUser")
        self.gridLayout_10.addWidget(self.lblDbUser, 3, 0, 1, 1)
        self.lineEditDbUser = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEditDbUser.setObjectName("lineEditDbUser")
        self.gridLayout_10.addWidget(self.lineEditDbUser, 3, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.btnTestConnection = QtWidgets.QPushButton(self.groupBox_5)
        self.btnTestConnection.setObjectName("btnTestConnection")
        self.gridLayout_11.addWidget(self.btnTestConnection, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabDatabase, "")
        self.tabModelrepos = QtWidgets.QWidget()
        self.tabModelrepos.setObjectName("tabModelrepos")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tabModelrepos)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabModelrepos)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidgetModelRepos = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidgetModelRepos.setSelectionMode(
                QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidgetModelRepos.setSelectionBehavior(
                QtWidgets.QAbstractItemView.SelectRows)
        self.listWidgetModelRepos.setObjectName("listWidgetModelRepos")
        self.horizontalLayout_2.addWidget(self.listWidgetModelRepos)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnAddModelRepo = QtWidgets.QPushButton(self.groupBox_4)
        self.btnAddModelRepo.setEnabled(True)
        self.btnAddModelRepo.setObjectName("btnAddModelRepo")
        self.verticalLayout_2.addWidget(self.btnAddModelRepo)
        self.btnDeleteModelRepo = QtWidgets.QPushButton(self.groupBox_4)
        self.btnDeleteModelRepo.setEnabled(False)
        self.btnDeleteModelRepo.setObjectName("btnDeleteModelRepo")
        self.verticalLayout_2.addWidget(self.btnDeleteModelRepo)
        self.btnEditModelRepo = QtWidgets.QPushButton(self.groupBox_4)
        self.btnEditModelRepo.setEnabled(False)
        self.btnEditModelRepo.setObjectName("btnEditModelRepo")
        self.verticalLayout_2.addWidget(self.btnEditModelRepo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_13.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabModelrepos, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Options)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setStandardButtons(
                QtWidgets.QDialogButtonBox.Cancel |
                QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 1)

        self.retranslateUi(Options)
        self.tabWidget.setCurrentIndex(3)
        self.buttonBox.rejected.connect(Options.reject)
        self.buttonBox.accepted.connect(Options.accept)
        QtCore.QMetaObject.connectSlotsByName(Options)

    def retranslateUi(self, Options):
        _translate = QtCore.QCoreApplication.translate
        Options.setWindowTitle(_translate("Options", " Options"))
        self.groupBox.setTitle(_translate("Options", "General options "))
        self.label.setText(_translate("Options", "Projects management: "))
        self.btnBrowseProjectsDatabase.setText(_translate("Options", "Browse"))
        self.btnBrowseProjectsRootDir.setText(_translate("Options", "Browse"))
        self.label_11.setText(
                _translate("Options", "Projects root directory: "))
        self.btnTestProjectDB.setText(
                _translate("Options", "Test projects database"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral),
                                  _translate("Options", "General"))
        self.groupBox_3.setTitle(_translate("Options", "Import application"))
        self.label_8.setText(_translate("Options", "Jar file: "))
        self.btnBrowseImportJar.setText(_translate("Options", "Browse"))
        self.groupBox_2.setTitle(_translate("Options", "VM arguments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabImport),
                                  _translate("Options", "Import"))
        self.groupBox_5.setTitle(_translate("Options", "Import database"))
        self.lblDbAdminPwd.setText(_translate("Options", "Admin password"))
        self.lblDbAdmin.setText(_translate("Options", "Admin"))
        self.lblDbPort.setText(_translate("Options", "Port"))
        self.lblDbUserPwd.setText(_translate("Options", "Password"))
        self.lblDbDatabase.setText(_translate("Options", "Database"))
        self.lblDbHost.setText(_translate("Options", "Host "))
        self.lblDbUser.setText(_translate("Options", "Username"))
        self.btnTestConnection.setText(_translate("Options", "Test connection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDatabase),
                                  _translate("Options", "Database"))
        self.groupBox_4.setTitle(_translate("Options", "Model repositories "))
        self.btnAddModelRepo.setText(_translate("Options", "Add"))
        self.btnDeleteModelRepo.setText(_translate("Options", "Delete"))
        self.btnEditModelRepo.setText(_translate("Options", "Edit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabModelrepos),
                                  _translate("Options", "Model repositories"))
